### ISSUE TITLE
Question about _C module from diff_gaissian_rasterization_df! 

### ISSUE THREAD

**Issue by yjl010228** [juno181/Ex4DGS#11]
Respect aurhors!After reading your paper, I feel it is very meaningful and interesting.
But when I debug train.py at the line of `render_pkg = render(viewpoint_cam, gaussians, pipe, bg, near=dataset.near, far=dataset.far)`, I meet an error like this:
![image](https://github.com/user-attachments/assets/0199c300-4bd8-407d-9466-3f0dfc7f2dcd)
![image](https://github.com/user-attachments/assets/ffdba96f-a7b6-40c2-bb69-4aaa925e52ac)
I notice that _C module  dose not in the diff_gaissian_rasterization_df and dose it mean I need to compile and install this module?I do try to run `python setup.py build_ext --inplace` to get the _C module, but I failed. The partial error is like this:
![image](https://github.com/user-attachments/assets/f893a631-811e-426b-958d-8b9aa89103e4)
 The above is what I want to say about my doubts. We look forward to your reply sincerely！

**Comment by DrawingProcess** [comment]
How to solved it?
