### ISSUE TITLE
Parameter setting for the MeetRoom dataset

### ISSUE THREAD

**Issue by turandai** [juno181/Ex4DGS#12]
Hi, thank you very much for opening source your wonderful work. I am trying to run it on the MeetRoom dataset, which is less complicated in scene settings but contains larger motion than N3DV dataset. I got unsatisfactory results using the default config file n3v_base.json. It would be wonderful if you can proviede some hint on how to improve the reconstruction quality. Thank you very much!
![image](https://github.com/user-attachments/assets/c47237a1-dd30-45bc-83ec-db568990b679)

**Comment by turandai** [comment]
Sorry, it turned out to be my own problem with data loading. Problem solved now.

**Comment by vikramsandu** [comment]
@turandai  What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.

**Comment by juno181** [comment]
> @turandai What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.

Hello. This issue seems to be due to different reasons. Learning all 300 frames of the Technicolor Dataset is unlikely to work well because the scene is complex and involves fast motion with a large number of images. Unfortunately, I could not find any work that trained all 300 frames. Instead, I recommend breaking it down into 100-frame sequences.

**Comment by turandai** [comment]
> > @turandai What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.
> 
> Hello. This issue seems to be due to different reasons. Learning all 300 frames of the Technicolor Dataset is unlikely to work well because the scene is complex and involves fast motion with a large number of images. Unfortunately, I could not find any work that trained all 300 frames. Instead, I recommend breaking it down into 100-frame sequences.

Actually I got quite good results for 300 frames in technicolor using your default configs. It seems better than many of other methods.

**Comment by vikramsandu** [comment]
> > > @turandai What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.
> > 
> > 
> > Hello. This issue seems to be due to different reasons. Learning all 300 frames of the Technicolor Dataset is unlikely to work well because the scene is complex and involves fast motion with a large number of images. Unfortunately, I could not find any work that trained all 300 frames. Instead, I recommend breaking it down into 100-frame sequences.
> 
> Actually I got quite good results for 300 frames in technicolor using your default configs. It seems better than many of other methods.

Ohh Great. But how good? For me, the moving object appears blurry. Here are few rendered samples from Painter Scene. This is trained using default settings for 300 frames and Test camera ID is 10. Did you get the similar or better results? Thanks,
![Painter_frame_00032_10](https://github.com/user-attachments/assets/37478f9a-df53-4d57-9428-18c4306b720f)
![Painter_frame_00064_10](https://github.com/user-attachments/assets/c76c1fc8-8c55-4d87-99a3-e38aa363e474)
![Painter_frame_00084_10](https://github.com/user-attachments/assets/0a675b71-c4e8-48bb-b7c6-516eecbd4b3e)
![Painter_frame_00257_10](https://github.com/user-attachments/assets/83e22f38-5de3-4772-8539-c9f44928bf4d)

**Comment by juno181** [comment]
> > > > @turandai What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.
> > > 
> > > 
> > > Hello. This issue seems to be due to different reasons. Learning all 300 frames of the Technicolor Dataset is unlikely to work well because the scene is complex and involves fast motion with a large number of images. Unfortunately, I could not find any work that trained all 300 frames. Instead, I recommend breaking it down into 100-frame sequences.
> > 
> > 
> > Actually I got quite good results for 300 frames in technicolor using your default configs. It seems better than many of other methods.
> 
> Ohh Great. But how good? For me, the moving object appears blurry. Here are few rendered samples from Painter Scene. This is trained using default settings for 300 frames and Test camera ID is 10. Did you get the similar or better results? Thanks, !

In my opinion, in the painter scene, the moving object is rendered blurry because it is faster than the speed that the model can handle (making it difficult to temporally match). I think that this should be combined with additional regularization, such as [MotionGS](https://ruijiezhu94.github.io/MotionGS_page/), to handle this.

**Comment by chenj02** [comment]
> > > @turandai What was the issue? I also got unsatisfactory results for Technicolor Dataset when trained for 300 frames. @juno181 Any suggestions? Thanks in advance.
> > 
> > 
> > Hello. This issue seems to be due to different reasons. Learning all 300 frames of the Technicolor Dataset is unlikely to work well because the scene is complex and involves fast motion with a large number of images. Unfortunately, I could not find any work that trained all 300 frames. Instead, I recommend breaking it down into 100-frame sequences.
> 
> Actually I got quite good results for 300 frames in technicolor using your default configs. It seems better than many of other methods.

Hi, how do you achieve this？if you only use default config？
