### ISSUE TITLE
The number of frames used in Training for technicolor.

### ISSUE THREAD

**Issue by vikramsandu** [juno181/Ex4DGS#6]
First of all, great work! In the preprocess_all_techni.sh file, you specified a duration (end_frame - start_frame) of 50. This suggests that the number of frames per camera is 50. Do the results mentioned in the paper follow the same setup?

**Comment by juno181** [comment]
The reason for using only 50 frames is to follow the evaluation protocol from previous papers (the same setup as [HyperReel](https://arxiv.org/pdf/2301.02238)). For results using different frames, I have specified the frames used in the paper.
