### ISSUE TITLE
how to train my own datasets

### ISSUE THREAD

**Issue by KL-2** [juno181/Ex4DGS#7]
Hello, how do I train my own datasets?Looking forward to your reply.

**Comment by KL-2** [comment]
I followed STG https://github.com/oppo-us-research/SpacetimeGaussians/issues/55#issuecomment-2185372592
made some changes on Ex4DGS/scene/dataset_readers.py
`
def readColmapCamerasTechnicolor(cam_extrinsics, cam_intrinsics,source_path, near, far, args,  startime=0,  endtime=-1):
    scene_name = os.path.basename(source_path)
    if scene_name =="Painter":
        start_idx = 0
    else:
        start_idx = 1
    cam_infos = []
    totalcamname = []
    for idx, key in enumerate(cam_extrinsics): # first is cam20_ so we strictly sort by camera name
        extr = cam_extrinsics[key]
        intr = cam_intrinsics[extr.camera_id]
        totalcamname.append(extr.name)
    
    sortedtotalcamelist =  natsort.natsorted(totalcamname)
    sortednamedict = {}
    for i in  range(len(sortedtotalcamelist)):
        sortednamedict[sortedtotalcamelist[i]] = i # map each cam with a number

    for idx, key in enumerate(cam_extrinsics): # first is cam20_ so we strictly sort by camera name
        sys.stdout.write('\r')
        # the exact output you're looking for:
        sys.stdout.write("Reading camera {}/{}".format(idx+1, len(cam_extrinsics)))
        sys.stdout.flush()

        extr = cam_extrinsics[key]
        intr = cam_intrinsics[extr.camera_id]
        height = intr.height
        width = intr.width

        uid = intr.id
        R = np.transpose(qvec2rotmat(extr.qvec))
        T = np.array(extr.tvec)

        if intr.model=="SIMPLE_PINHOLE":
            focal_length_x = intr.params[0]
            FovY = focal2fov(focal_length_x, height)
            FovX = focal2fov(focal_length_x, width)
        elif intr.model=="PINHOLE":
            focal_length_x = intr.params[0]
            focal_length_y = intr.params[1]
            FovY = focal2fov(focal_length_y, height)
            FovX = focal2fov(focal_length_x, width)
        else:
            assert False, "Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!"

        for j in range(startime, endtime):
            image_path = os.path.join(source_path, os.path.basename(extr.name))
            # print("sdjfhksjfhsdkjfhsjk"+image_path)
            image_name = os.path.basename(image_path).split(".")[0]
            image_path = image_path.replace("colmap_"+str(startime), "colmap_{}".format(j), 1)


        
            cxr =   ((intr.params[2] )/  width - 0.5) 
            cyr =   ((intr.params[3] ) / height - 0.5) 

            K = np.eye(3)
            K[0, 0] = focal_length_x #* 0.5
            K[0, 2] = intr.params[2] #* 0.5 
            K[1, 1] = focal_length_y #* 0.5
            K[1, 2] = intr.params[3] #* 0.5



            halfH = round(height / 2.0 )
            halfW = round(width / 2.0 )
            
            assert os.path.exists(image_path), "Image {} does not exist!".format(image_path)

            
            image = Image.open(image_path)

            
            if j == startime:
                cam_info = CameraInfo2(uid=uid, R=R, T=T, FovY=FovY, FovX=FovX,image_path=image_path, image_name=image_name, width=width, height=height, near=near, far=far, timestamp=(j-startime)/(endtime-startime), pose=1, hpdirecitons=1, cxr=cxr, cyr=cyr)
                
            else:
                cam_info = CameraInfo2(uid=uid, R=R, T=T, FovY=FovY, FovX=FovX, image_path=image_path, image_name=image_name, width=width, height=height, near=near, far=far, timestamp=(j-startime)/(endtime-startime), pose=None, hpdirecitons=None,  cxr=cxr, cyr=cyr)
            cam_infos.append(cam_info)
    sys.stdout.write('\n')
    return cam_infos

`
and
`
def readColmapSceneInfoTechnicolor(path, images, eval, args):
    colmap_path = os.path.join(path, "colmap_" + str(int(args.start_timestamp)))

    try:
        cameras_extrinsic_file = os.path.join(colmap_path, "sparse/0", "images.bin")
        cameras_intrinsic_file = os.path.join(colmap_path, "sparse/0", "cameras.bin")
        cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
        cam_intrinsics = read_intrinsics_binary(cameras_intrinsic_file)
    except:
        cameras_extrinsic_file = os.path.join(colmap_path, "sparse/0", "images.txt")
        cameras_intrinsic_file = os.path.join(colmap_path, "sparse/0", "cameras.txt")
        cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
        cam_intrinsics = read_intrinsics_text(cameras_intrinsic_file)

    near = 0.01
    far = 100

    reading_dir = "images" if images == None else images
    cam_infos_unsorted = readColmapCamerasTechnicolor(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, source_path=os.path.join(path,"colmap_0",reading_dir), 
                                                      near=near, far=far, args=args, startime=args.start_timestamp, endtime=args.end_timestamp)
    cam_infos = sorted(cam_infos_unsorted.copy(), key = lambda x : x.image_name)

    if eval:
        train_cam_infos = [_ for _ in cam_infos if "_10.png" not in _.image_name]
        test_cam_infos = [_ for _ in cam_infos if "_10.png" in _.image_name]
        if len(test_cam_infos) > 0:
            uniquecheck = []
            for cam_info in test_cam_infos:
                if cam_info.uid not in uniquecheck:
                    uniquecheck.append(cam_info.uid)
            assert len(uniquecheck) == 1 
            
            sanitycheck = []
            for cam_info in train_cam_infos:
                if cam_info.uid not in sanitycheck:
                    sanitycheck.append(cam_info.uid)
            for testname in uniquecheck:
                assert testname not in sanitycheck
        else:
            first_cam = cam_infos[0].image_name
            print("do custom loader training, select first cam as test frame: ", first_cam)
            cam_infos = natsort.natsorted(cam_infos_unsorted.copy(), key = lambda x : x.image_name)
            train_cam_infos = [_ for _ in cam_infos if first_cam not in _.image_name]
            test_cam_infos = [_ for _ in cam_infos if first_cam in _.image_name]

    else:
        train_cam_infos = cam_infos
        test_cam_infos = cam_infos[:4]

    nerf_normalization = getNerfppNorm(train_cam_infos)
    
    # normalization
    for c in train_cam_infos:
        c.T = c.T / nerf_normalization['radius']
    for c in test_cam_infos:
        c.T = c.T / nerf_normalization['radius']

    ply_path = os.path.join(colmap_path, "sparse", "0", "points3D.ply")
    bin_path = os.path.join(colmap_path, "sparse", "0", "points3D.bin")
    txt_path = os.path.join(colmap_path, "sparse", "0", "points3D.txt")
    
    if not os.path.exists(ply_path):
        print("Converting point3d.bin to .ply, will happen only the first time you open the scene.")
        try:
            xyz, rgb, _ = read_points3D_binary(bin_path)
        except:
            xyz, rgb, _ = read_points3D_text(txt_path)
        xyz = xyz / nerf_normalization['radius']
        storePly(ply_path, xyz, rgb)
    try:
        pcd = fetchPly(ply_path)
    except:
        pcd = None

    nerf_normalization['radius'] = 1

    scene_info = SceneInfo(point_cloud=pcd,
                           train_cameras=train_cam_infos,
                           test_cameras=test_cam_infos,
                           nerf_normalization=nerf_normalization,
                           ply_path=ply_path)
    
    return scene_info
`
I'm still running my dataset,I don't know if it's completely ok.
Hope some help for someone meet the same question

**Comment by YJ-LIAO** [comment]
Did you complete it?
