### ISSUE TITLE
how to render trajectory and dynamic

### ISSUE THREAD

**Issue by KL-2** [juno181/Ex4DGS#9]
Great Job!
Can you provide some ways to render like trajectory and dynamic in the following gif

![image](https://github.com/user-attachments/assets/724cd65b-adc4-4e8d-af26-bfda7d45ed34)

**Comment by sranqiu** [comment]
I also want to know how to render and see the effect

**Comment by juno181** [comment]
You can render points by adjusting the scaling of the Gaussian. For a visualization of a trajactory, please refer [Dynamic3DGaussians](
https://github.com/JonathonLuiten/Dynamic3DGaussians/blob/main/visualize.py).
